# Generated by Django 5.2.1 on 2025-06-12 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atoll',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('island_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('admin_island', 'ADMIN ISLAND'), ('maale', 'MAALE')], max_length=250)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('atoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islandsmv.atoll')),
            ],
        ),
    ]
