# Generated by Django 5.2.3 on 2025-07-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islandsmv', '0003_rename_atoll_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atoll',
            name='name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
