name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.11', '3.12' ]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd djangoapp
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd djangoapp
          python manage.py test
